theme: jekyll-theme-minimal
logo: https://github.com/xaviergp/littlebrain/blob/master/logo_littlebrain.png
title: Download Xavier Guell's papers
description: This link is sent directly from Xavier Guell, for personal use only.
